---
- name: creat user
  hosts: xen
  gather_facts: False
  remote_user: root
  vars_prompt:
    - name: "user_name"
      prompt: "Enter user name"
      private: no
    - name: "user_password"
      prompt: "Enter user password"
      encrypt: "sha512_crypt"
      private: no
      confirm: yes
  tasks:
    - name: create system user
      user:
        name: "{{user_name}}"
        password: "{{user_password}}"
        state: present
        shell: /bin/bash
        createhome: yes
        generate_ssh_key: yes
      tags: create_system_user

    - name: update sudoers file
      lineinfile:
        path: /etc/sudoers
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
        insertafter: EOF
        regexp: '^{{ user_name }} .*'
        state: present
        backrefs: yes
      tags: [create_system_user,update_sudoers]

    - name: set authorized keys
      authorized_key:
        user: "{{user_name}}"
        key: "{{lookup('file','/home/{{ user_name }}/.ssh/id_rsa.pub')}}"
        state: present
      tags: [create_system_user,update_sudoers,set_authorized_key]